#!/bin/sh

MPD_DOWNLOAD_DIR="${HOME}/music/youtube"

usage() {
	echo "`basename $0`[-h] <query>"
}

ys() {
	num=3
	regex='^.*<a href="\(/watch[^"]*\)"[^>]*>\([^<]*\)</a>.*$'
	optout='\2 - http://youtube.com\1'

	while getopts "hn:tu" OPT; do
		case $OPT in
				n) num=$OPTARG;;
				t) output='\2';;
				u) output='http://youtube.com\1';;
				h) usage long; exit 0;;
				*) usage; exit 1;;
		esac
	done

	shift $((OPTIND -1))

	query=$(echo $@ | tr ' ' '+')
	url="https://www.youtube.com/results?search_query=${query}"

	curl -s "$url" | sed -n "s,$regex,$output,p" | sed ${num}q
}

# exit if no argumnet given
test $# -eq 0 && usage && exit 1

# single search terms or multi
test $# -gt 1 && uri=$(ys -n1 -u $@) || uri=$1

# exit if no uri found
if test -z "$uri"; then
		echo "no result found"
		exit 1
fi

# move to target dir 
test -d $MPD_DOWNLOAD_DIR && cd $MPD_DOWNLOAD_DIR

# download and get audio track
youtube-dl -q -x -o '%(title)s.%(ext)s' "$uri"

# update mpd if running
pgrep mpd > /dev/null 2>&1 && mpc -q update
